### ISSUE TITLE
Default layout

### ISSUE THREAD

**Issue by SPROgster** [dervishe-/genBerry#1]
Default kb layout of builded system is azerty (fr in /etc/conf.d/keymaps) o.0
I think, must be an option to select default layout

**Comment by dervishe-** [comment]
Yep because i'm french ;-)
I forgot to put it in us by default. I will do it and add the possibility to choose the layout and the locale. Actually just type: "loadkeys us" or for your layout: "loqdkeys us"

**Comment by SPROgster** [comment]
Thx.
PS and i'm russian. =)

**Comment by dervishe-** [comment]
Sorry for that, i was involved in another project. A new version s coming without the need of downloading stage4 and more customizable.
