### ISSUE TITLE
Kernel building tools installed ? [FAIL]

### ISSUE THREAD

**Issue by stefson** [dervishe-/genBerry#3]
executing the imagebuilder script fails always at the point where it is checking for the kernel building tools being installed. 

By reading through the scripts it seems as if "imagetool-uncompressed.py" is needed. But at which place is the script looking for it? Where do I have to store it?

**Comment by dervishe-** [comment]
In fact, this checking is done here: https://github.com/dervishe-/genBerry/blob/master/helpers#L96
The script use `which` command to locate  "imagetool-uncompressed.py", thus you only have to install it with your distro's package manager. the `which` command search in $PATH. Thus you can also install it where you want and include its location in your PATH variable. The script is available here: https://github.com/raspberrypi/tools/tree/master/mkimage

**Comment by stefson** [comment]
For gentoo as a host system one should emerge sys-boot/raspberrypi-mkimage, because in fact executable python scripts are stored into /usr/lib/python-exec/pythonX.X/ from where they are symlinked into /usr/bin. The ebuild takes care of this, so that imagetool-uncompressed.py is found by which

**Comment by dervishe-** [comment]
Yes it's always better to install tool with the distro package manager :)
Btw, tonight i will update the version of the image.
