### ISSUE TITLE
genBerry_v7.tar.xz.md5sum cannot be found (and your signatur as well)

### ISSUE THREAD

**Issue by stefson** [dervishe-/genBerry#4]
can you please reenable the download of these files which you seem to host?

**Comment by dervishe-** [comment]
Hello, i'm currently migrating the files, but iḿ busy in the moment. I will fix that soon (in a couple of week).

**Comment by stefson** [comment]
It would be great to have the files back. 

I wonder if you ever got a working X with your stage4, and if you ever had, if you can publish a readme or something like that? :)

**Comment by dervishe-** [comment]
Sorry for that, i was involved in another project. A new version s coming without the need of downloading stage4.
