### ISSUE TITLE
https://debrouillonet.org//genBerry_v8.tar.xz.md5sum missing

### ISSUE THREAD

**Issue by kde99** [dervishe-/genBerry#5]
Hello,

could you upload the files again because they seem to be missing on your site and I'd like to install gentoo. Also #4 would be happy too probably. BTW is the rpi3 version aarch64 or is it just aarch32?

**Comment by dervishe-** [comment]
Sorry for that, i was involved in another project. A new version s coming without the need of downloading stage4.
